# Generated by Django 6.0.1 on 2026-03-26 09:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('recent', 'Recent Updates'), ('guideline', 'Good Guideline'), ('advocates', 'For Advocates'), ('common', 'For Common People'), ('judiciary', 'For Judiciary')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='pages/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JudgmentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('court_name', models.CharField(max_length=200)),
                ('judgment_date', models.DateField()),
                ('case_number', models.CharField(max_length=150)),
                ('judges', models.CharField(blank=True, max_length=300)),
                ('summary', models.TextField()),
                ('full_content', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='judgments/images/')),
                ('pdf_file', models.FileField(blank=True, help_text='Upload judgment PDF', null=True, upload_to='judgments/pdfs/')),
                ('read_more_link', models.URLField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judgments', to='news.category')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='LawActPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Law/Act headline (e.g., New Criminal Law Amendments 2024)', max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('act_name', models.CharField(help_text='Official name of the Act', max_length=250)),
                ('act_number', models.CharField(blank=True, help_text='e.g., Act No. 45 of 2024', max_length=100)),
                ('enactment_date', models.DateField(help_text='Date of enactment/notification')),
                ('ministry', models.CharField(blank=True, help_text='e.g., Ministry of Home Affairs', max_length=200)),
                ('summary', models.TextField(help_text='Short summary (2-3 sentences)')),
                ('full_content', models.TextField(help_text='Full article about the law/act')),
                ('key_provisions', models.TextField(blank=True, help_text='Key highlights/provisions')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='laws/images/')),
                ('pdf_file', models.FileField(blank=True, help_text='Upload Act PDF', null=True, upload_to='laws/pdfs/')),
                ('read_more_link', models.URLField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=300)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laws', to='news.category')),
            ],
            options={
                'verbose_name': 'Law/Act Post',
                'verbose_name_plural': 'Law/Act Posts',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='news.category')),
            ],
            options={
                'verbose_name_plural': 'Sub-Categories',
                'ordering': ['parent_category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ArticlePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Article headline', max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('summary', models.TextField(help_text='Short summary (2-3 sentences)')),
                ('full_content', models.TextField(help_text='Full article content')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='articles/images/')),
                ('read_more_link', models.URLField(blank=True, help_text='External link for more details', null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=300)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.subcategory')),
            ],
            options={
                'verbose_name': 'Article Post',
                'verbose_name_plural': 'Article Posts',
                'ordering': ['-published_date'],
            },
        ),
    ]
