# Generated by Django 6.0.1 on 2026-03-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvocateGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('category', models.CharField(choices=[('bail', 'Bail Process'), ('fir', 'FIR Drafting'), ('court', 'Court Procedure'), ('civil', 'Civil Law'), ('criminal', 'Criminal Law'), ('evidence', 'Evidence & Documentation'), ('appeal', 'Appeals & Revision'), ('other', 'Other')], default='other', max_length=50)),
                ('content', models.TextField()),
                ('youtube_link', models.URLField(blank=True, help_text='Paste full YouTube URL here', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Advocate Guide',
                'verbose_name_plural': 'Advocate Guides',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CitizenGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('category', models.CharField(choices=[('fir_refusal', 'Police FIR Refusal'), ('divorce', 'Divorce & Separation'), ('property', 'Property Disputes'), ('domestic', 'Domestic Violence'), ('consumer', 'Consumer Rights'), ('labour', 'Labour & Employment'), ('cyber', 'Cyber Crime'), ('rent', 'Rent & Tenancy'), ('other', 'Other')], default='other', max_length=50)),
                ('content', models.TextField()),
                ('youtube_link', models.URLField(blank=True, help_text='Paste full YouTube URL here', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Citizen Guide',
                'verbose_name_plural': 'Citizen Guides',
                'ordering': ['-created_at'],
            },
        ),
    ]
