# Generated by Django 6.0.1 on 2026-03-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_advocateguide_citizenguide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocateguide',
            name='content',
            field=models.TextField(help_text='Full guide content (HTML supported)'),
        ),
        migrations.AlterField(
            model_name='advocateguide',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='Paste full YouTube URL', null=True),
        ),
        migrations.AlterField(
            model_name='citizenguide',
            name='content',
            field=models.TextField(help_text='Full guide content (HTML supported)'),
        ),
        migrations.AlterField(
            model_name='citizenguide',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='Paste full YouTube URL', null=True),
        ),
    ]
